### PR TITLE
Fix email provider table sorting

### PR DESCRIPTION
**Pull request by Shifterovich**
https://github.com/privacytoolsIO/privacytools.io/pull/111

> Price `data-value`'s are in USD. As currencies' values change, I rounded the converted values.

### CODE REVIEW

**Comment by kewde** [comment]
Approved, seems right to me. Should be tested once merged!

**Comment by Shifterovich** [comment]
[Test it now](https://htmlpreview.github.io/?https://raw.githubusercontent.com/Shifterovich/privacytools.io/1e608b9484e9d4e053bddc86ff04af9fa5301ffc/index.html).

**Comment by kewde** [comment]
That's a trick I taught you :wink:

**Comment by kewde** [comment]
Tested, looks good.

**Comment by Shifterovich** [comment]
Heh.

**Pull request merged**
